"""empty message

Revision ID: 4fc5b1d875fc
Revises: 
Create Date: 2021-08-07 21:46:01.283691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc5b1d875fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('qd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expenses', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ecd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('edc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('surge_markup', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crime_markup', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rider_star_markup', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driver_star_markup', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low_battery_markup', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ban_riders_rule', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ban_drivers_rule', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driver_ad_expense', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rider_ad_expense', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rider_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driver_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rider_satisfaction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driver_satisfaction', sa.Float(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('event_type')
        batch_op.drop_column('trigger_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('passed_prescreen')
        batch_op.drop_column('condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('passed_prescreen', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('trigger_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('driver_satisfaction')
        batch_op.drop_column('rider_satisfaction')
        batch_op.drop_column('driver_profit')
        batch_op.drop_column('rider_profit')
        batch_op.drop_column('total_profit')
        batch_op.drop_column('rider_ad_expense')
        batch_op.drop_column('driver_ad_expense')
        batch_op.drop_column('ban_drivers_rule')
        batch_op.drop_column('ban_riders_rule')
        batch_op.drop_column('low_battery_markup')
        batch_op.drop_column('driver_star_markup')
        batch_op.drop_column('rider_star_markup')
        batch_op.drop_column('crime_markup')
        batch_op.drop_column('surge_markup')
        batch_op.drop_column('edc')
        batch_op.drop_column('ecd')
        batch_op.drop_column('pd')
        batch_op.drop_column('pc')
        batch_op.drop_column('expenses')
        batch_op.drop_column('vd')
        batch_op.drop_column('vc')
        batch_op.drop_column('qd')
        batch_op.drop_column('qc')

    # ### end Alembic commands ###
