"""empty message

Revision ID: ebccf812b176
Revises: 4fc5b1d875fc
Create Date: 2021-08-07 22:00:40.558057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebccf812b176'
down_revision = '4fc5b1d875fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mturk_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mturk_id', sa.VARCHAR(length=70), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
